---
- hosts: all
  become: true
  tasks:

  - name: install Prometheus
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - prometheus
      - prometheus-node-exporter
      - prometheus-alert-manager

  - name: Copy Prometheus configuration file
    copy:
       src: prometheus_ansible.yml
       dest: ~/prometheus/prometheus.yml
    notify:
       - restart prometheus

  handlers:
    - name: restart prometheus
      service:
        name: prometheus
        state: restarted

